Repository bcgov/jasper, pull requests merged in 2025-03, with the labels that each got.

#204 JASPER 267: Court-list auto-refresh and message
  web/src/components/courtlist/CourtListSearch.vue
  web/src/components/shared/Snackbar.vue
  web/src/stores/SnackbarStore.ts
  web/tests/components/courtList/CourtListSearch.test.ts
  web/tests/stores/SnackbarStore.test.ts
Labels: enhancement, javascript

#207 JASPER 238: Court-list data filter
  web/src/components/courtlist/CourtList.vue
  web/src/components/courtlist/CourtListSearch.vue
  web/src/components/courtlist/CourtListTableSearch.vue
  web/src/components/shared/Banner.vue
  web/tests/components/courtList/CourtListTableSearch.test.ts
  web/tests/components/shared/Banner.test.ts
Labels: enhancement, javascript

#205 JASPER-170: Design user maintenance function in JASPER (back end)
  .sonarcloud.properties
  api/Infrastructure/ServiceCollectionExtensions.cs
  api/Program.cs
  api/Services/EF/MigrationAndSeedService.cs
  api/Startup.cs
  api/api.csproj
  db/Contexts/JasperDbContext.cs
  db/Interceptors/AuditInterceptor.cs
  db/Models/EntityBase.cs
  db/Models/Group.cs
  db/Models/Permission.cs
  db/Models/Role.cs
  db/Models/User.cs
  db/Seeders/GroupSeeder.cs
  db/Seeders/PermissionSeeder.cs
  db/Seeders/RoleSeeder.cs
  db/Seeders/SeederBase.cs
  db/Seeders/SeederFactory.cs
  db/Seeders/UserSeeder.cs
  db/db.csproj
  docker/docker-compose.yaml
  docker/manage
Labels: enhancement, dependencies, .NET

#211 JASPER-315: Permission read and update operations
  api/Controllers/PermissionsController.cs
  api/Infrastructure/ServiceCollectionExtensions.cs
  api/Mappers/UserManagementProfile.cs
  api/Models/UserManagement/PermissionDto.cs
  api/Models/UserManagement/PermissionUpdateDto.cs
  api/Services/PermissionService.cs
  api/Services/ServiceBase.cs
  db/Repositories/PermissionRepository.cs
  db/Repositories/RepositoryBase.cs
Labels: enhancement, .NET

#210 JASPER 260: Court-list Card - See more about this location
  api/Mappers/LocationProfile.cs
  api/Models/Location/Location.cs
  api/Models/Location/Locations.cs
  api/Services/LocationService.cs
  tests/api/Mappers/LocationProfileTests.cs
  tests/api/Models/Location/LocationTests.cs
  tests/api/Models/Location/LocationsTests.cs
  tests/api/Services/LocationServiceTests.cs
  web/src/components/courtlist/CourtListCard.vue
  web/src/types/common/index.ts
  web/tests/components/courtList/CourtListCard.test.ts
Labels: enhancement, javascript, .NET

#218 JASPER 277: Criminal Case Details Banner
  web/src/components/case-details/CourtFilesSelector.vue
  web/src/components/civil/CivilCaseDetails.vue
  web/src/components/criminal/CriminalCaseDetails.vue
  web/src/components/shared/CourtFilesSelector.vue
  web/src/stores/CourtFileSearchStore.ts
  web/tests/components/case-details/CourtFilesSelector.test.ts
Labels: enhancement, javascript

#219 Fix incorrect stylesheet import
  web/index.html
  web/src/components/civil/CivilCaseDetails.vue
Labels: bug, javascript

#220 JASPER-320: Roles CRUD operations
  api/Controllers/AccessControlManagementControllerBase.cs
  api/Controllers/PermissionsController.cs
  api/Controllers/RolesController.cs
  api/Infrastructure/OperationResult.cs
  api/Infrastructure/ServiceCollectionExtensions.cs
  api/Mappers/AccessControlManagementProfile.cs
  api/Mappers/UserManagementProfile.cs
  api/Models/AccessControlManagement/AccessControlManagementDto.cs
  api/Models/AccessControlManagement/PermissionDto.cs
  api/Models/AccessControlManagement/RoleDto.cs
  api/Models/UserManagement/PermissionDto.cs
  api/Models/UserManagement/PermissionUpdateDto.cs
  api/Services/AccessControlManagementServiceBase.cs
  api/Services/CourtListService.cs
  api/Services/PermissionService.cs
  api/Services/RoleService.cs
  api/Services/ServiceBase.cs
  api/Startup.cs
  api/Validators/AccessControlManagementDtoValidator.cs
  api/Validators/PermissionDtoValidator.cs
  api/Validators/RoleDtoValidator.cs
  api/api.csproj
  infrastructure/cloud/modules/SecretsManager/main.tf
  infrastructure/cloud/modules/SecretsManager/output.tf
  tests/api/Controllers/CourtListControllerTests.cs
  tests/api/Controllers/PermissionsControllerTests.cs
  tests/api/Controllers/RolesControllerTests.cs
  tests/api/Services/PermissionServiceTests.cs
  tests/api/Services/RoleServiceTests.cs
  tests/tests.csproj
Labels: enhancement, dependencies, .NET

#231 JASPER 321 and 331: Groups and Users CRUD Operations
  api/Controllers/GroupsController.cs
  api/Controllers/UsersController.cs
  api/Infrastructure/ServiceCollectionExtensions.cs
  api/Mappers/AccessControlManagementProfile.cs
  api/Models/AccessControlManagement/GroupDto.cs
  api/Models/AccessControlManagement/UserDto.cs
  api/Services/GroupService.cs
  api/Services/RoleService.cs
  api/Services/UserService.cs
  api/Validators/AccessControlManagementDtoValidator.cs
  api/Validators/GroupDtoValidator.cs
  api/Validators/PermissionDtoValidator.cs
  api/Validators/RoleDtoValidator.cs
  api/Validators/UserDtoValidator.cs
  db/Models/Group.cs
  db/Models/User.cs
  db/Repositories/PermissionRepository.cs
  tests/api/Controllers/GroupsControllerTests.cs
  tests/api/Controllers/PermissionsControllerTests.cs
  tests/api/Services/GroupServiceTests.cs
  tests/api/Services/RoleServiceTests.cs
  tests/api/Services/UserServiceTests.cs
  tests/api/Validators/AccessControlManagementValidatorTests.cs
  tests/api/Validators/GroupDtoValidatorTests.cs
  tests/api/Validators/PermissionDtoValidatorTests.cs
  tests/api/Validators/RoleDtoValidatorTests.cs
  tests/api/Validators/UserDtoValidatorTests.cs
Labels: enhancement, .NET

#230 JASPER 281: Criminal Case Details Summary
  web/src/components/case-details/CriminalSidePanel.vue
  web/src/components/case-details/DivisionBadge.vue
  web/src/components/case-details/Summary.vue
  web/src/components/criminal/CriminalCaseDetails.vue
  web/src/components/criminal/CriminalSentence.vue
  web/src/components/shared/FileMarkers.vue
  web/tests/components/case-details/CriminalSidePanel.test.ts
  web/tests/components/case-details/DivisionBadge.test.ts
  web/tests/components/case-details/Summary.test.ts
  web/tests/components/shared/FileMarkers.test.ts
Labels: enhancement, javascript

#232 Added stricter email validation check
  api/Validators/UserDtoValidator.cs
  tests/api/Validators/UserDtoValidatorTests.cs
Labels: bug

#233 JASPER-312: Implement Enforcement of Access Control checks
  api/Controllers/AuthController.cs
  api/Controllers/UsersController.cs
  api/Helpers/ClaimsTypes.cs
  api/Helpers/Extensions/ClaimsPrincipalExtensions.cs
  api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
  api/Infrastructure/Authorization/AuthorizationServiceCollectionExtension.cs
  api/Infrastructure/Authorization/PermissionHandler.cs
  api/Infrastructure/Authorization/PermissionRequirement.cs
  api/Infrastructure/Authorization/RequiresPermissionAttribute.cs
  api/Infrastructure/Authorization/RequiresPermissionFilter.cs
  api/Infrastructure/ServiceCollectionExtensions.cs
  api/Mappers/AccessControlManagementProfile.cs
  api/Models/AccessControlManagement/UserDto.cs
  api/Services/UserService.cs
  db/Contexts/JasperDbContext.cs
  db/Seeders/UserSeeder.cs
  docker/docker-compose.yaml
  infrastructure/cloud/modules/SecretsManager/main.tf
  infrastructure/cloud/modules/SecretsManager/output.tf
  tests/api/Controllers/AuthControllerTests.cs
  tests/api/Helpers/Extensions/ClaimsPrincipalExtensionsTests.cs
  tests/api/Infrastructure/Authorization/PermissionHandlerTests.cs
  tests/api/Services/UserServiceTests.cs
Labels: enhancement, .NET

#244 JASPER-344: Backend implementation to generate report
  api/Controllers/CourtListController.cs
  api/Infrastructure/ServiceCollectionExtensions.cs
  api/Models/CourtList/CourtListReportRequest.cs
  api/Services/CourtListService.cs
  api/Validators/CourtList/CourtListReportRequestValidator.cs
  pcss-client/Clients/ReportServicesClient.cs
  tests/api/Controllers/CourtListControllerTests.cs
  tests/api/Services/CourtListServiceTests.cs
  tests/api/Services/LookupServiceTests.cs
  tests/api/Validators/CourtList/CourtListReportRequestValidatorTests.cs
Labels: enhancement, .NET

#245 JASPER 283: Case-detail Accused Information
  web/public/styles/common.css
  web/src/components/case-details/Accused/Accused.vue
  web/src/components/case-details/Accused/AccusedPanel.vue
  web/src/components/case-details/Accused/Ban.vue
  web/src/components/case-details/CriminalSidePanel.vue
  web/src/components/case-details/Summary.vue
  web/src/utils/utils.ts
  web/tests/components/case-details/Accused/Accused.test.ts
  web/tests/components/case-details/Accused/AccusedPanel.test.ts
  web/tests/components/case-details/Accused/Ban.test.ts
  web/tests/components/case-details/CriminalSidePanel.test.ts
Labels: enhancement, javascript

#252 JASPER 283: Display correct Ban information
  web/src/components/case-details/Accused/Accused.vue
  web/src/components/case-details/Accused/Bans.vue
  web/src/components/criminal/CriminalCaseDetails.vue
  web/tests/components/case-details/Accused/Accused.test.ts
  web/tests/components/case-details/Accused/Bans.test.ts
Labels: javascript
