Repository bcgov/jasper, pull requests merged in 2025-06, with the labels that each got.

#340 JASPER-416: Case Details: "Sealed" message showing on all files once a sealed file is loaded.
  web/src/components/civil/CivilCaseDetails.vue
Labels: bug, javascript

#348 JASPER-404: Judicial Binder: Define the structure for storing data related to the judicial binder
  api/Controllers/AccessControlManagementControllerBase.cs
  api/Controllers/CodesController.cs
  api/Helpers/ClaimsTypes.cs
  api/Helpers/Extensions/ClaimsPrincipalExtensions.cs
  api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
  api/Infrastructure/Authentication/SiteMinderAuthenticationHandler.cs
  api/Infrastructure/OperationResult.cs
  api/Infrastructure/ServiceCollectionExtensions.cs
  api/Models/AccessControlManagement/AccessControlManagementDto.cs
  api/Models/AccessControlManagement/GroupDto.cs
  api/Models/AccessControlManagement/PermissionDto.cs
  api/Models/AccessControlManagement/RoleDto.cs
  api/Models/AccessControlManagement/UserDto.cs
  api/Models/BaseDto.cs
  api/Models/BinderDocumentDto.cs
  api/Models/BinderDto.cs
  api/Models/TagDto.cs
  api/Services/AccessControlManagementServiceBase.cs
  api/Validators/BaseDtoValidator.cs
  api/Validators/GroupDtoValidator.cs
  api/Validators/PermissionDtoValidator.cs
  api/Validators/RoleDtoValidator.cs
  api/Validators/UserDtoValidator.cs
  db/Contants/LabelConstants.cs
  db/Contexts/JasperDbContext.cs
  db/Models/Binder.cs
  db/Models/BinderDocument.cs
  db/Models/Tag.cs
  tests/api/Controllers/AuthControllerTests.cs
  tests/api/Helpers/Extensions/ClaimsPrincipalExtensionsTests.cs
  tests/api/Infrastructure/Authorization/PermissionHandlerTests.cs
  tests/api/Validators/BaseDtoValidatorTests.cs
Labels: enhancement, .NET

#349 Migrate from devcontainers-contrib to devcontainers-extra
  .devcontainer/devcontainer.json
Labels: dependencies

#357 JASPER 339 - Court-list updates
  web/public/styles/common.css
  web/src/components/courtlist/CourtList.vue
  web/src/components/courtlist/CourtListTable.vue
  web/src/components/courtlist/CourtListTableActionBarGroup.vue
  web/src/components/shared/TooltipIcon.vue
  web/src/components/shared/table/ActionBar.vue
  web/src/utils/utils.ts
  web/tests/components/courtList/CourtListTableActionBarGroup.test.ts
  web/tests/components/shared/table/ActionBar.test.ts
Labels: enhancement, javascript

#358 JASPER 424: Sentence-order - Remove 10 item table limit
  web/src/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsTable.vue
Labels: bug, javascript

#362 JASPER 421: Only show file markers that are "set"
  web/src/components/shared/FileMarkers.vue
  web/tests/components/shared/FileMarkers.test.ts
Labels: javascript

#359 JASPER-405 and JASPER-406: Service and Controller Layer
  api/Controllers/AccessControlManagementControllerBase.cs
  api/Controllers/BindersController.cs
  api/Controllers/FilesController.cs
  api/Controllers/GroupsController.cs
  api/Controllers/PermissionsController.cs
  api/Controllers/RolesController.cs
  api/Helpers/Extensions/ClaimsPrincipalExtensions.cs
  api/Helpers/Extensions/DictionaryExtensions.cs
  api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
  api/Infrastructure/Authorization/VcCivilFileAccessHandler.cs
  api/Infrastructure/Mappings/BinderMapping.cs
  api/Infrastructure/ServiceCollectionExtensions.cs
  api/Models/BinderDocumentDto.cs
  api/Models/BinderDto.cs
  api/Processors/BinderFactory.cs
  api/Processors/BinderProcessorBase.cs
  api/Processors/JudicialBinderProcessor.cs
  api/Services/BinderService.cs
  api/Services/CrudServiceBase.cs
  api/Services/Files/FilesService.cs
  api/Services/GroupService.cs
  api/Services/PermissionService.cs
  api/Services/RoleService.cs
  api/Services/UserService.cs
  api/Validators/BinderDtoValidator.cs
  api/api.csproj
  db/Contants/CollectionNameConstants.cs
  db/Contexts/JasperDbContext.cs
  db/Models/Binder.cs
  db/Models/BinderDocument.cs
  db/Models/Group.cs
  db/Models/Permission.cs
  db/Models/Role.cs
  db/Models/Tag.cs
  db/Models/User.cs
  db/Repositories/PermissionRepository.cs
  db/Repositories/RepositoryBase.cs
  tests/api/Controllers/FilesControllerTests.cs
  tests/api/Controllers/GroupsControllerTests.cs
  tests/api/Controllers/PermissionsControllerTests.cs
  tests/api/Controllers/RolesControllerTests.cs
  tests/api/Services/BinderServiceTests.cs
Labels: enhancement, .NET

#369 JASPER 361: Case-details merged documents view/Document Outline
  web/src/components/case-details/civil/CivilDocumentsView.vue
  web/src/components/case-details/criminal/CriminalDocumentsView.vue
  web/src/components/documents/DocumentUtils.ts
  web/src/components/documents/NutrientContainer.vue
  web/src/components/shared.ts
  web/src/router/index.ts
  web/tests/components/case-details/civil/CivilDocumentsView.test.ts
  web/tests/components/case-details/criminal/CriminalDocumentsView.test.ts
  web/tests/components/documents/DocumentUtils.test.ts
  web/tests/components/documents/NutrientContainer.test.ts
Labels: javascript

#377 JASPER 350: Court-list criminal appearance expanded panel
  api/Services/Files/CriminalFilesService.cs
  web/package-lock.json
  web/package.json
  web/src/components/case-details/common/AppearancesView.vue
  web/src/components/courtfilesearch/CourtFileSearchResult.vue
  web/src/components/courtlist/CourtListCriminalDetails.vue
  web/src/components/courtlist/CourtListTable.vue
  web/src/services/FilesService.ts
  web/tests/components/courtList/CourtListCriminalDetails.test.ts
Labels: javascript, .NET
