Repository bcgov/jasper, pull requests merged in 2025-09, with the labels that each got.

#474 JASPER-567: Show JASPER application logo
  web/index.html
  web/src/App.vue
  web/src/assets/jasper-logo.svg
Labels: javascript

#482 JASPER-548: Case Details: Civil: Document Filtering by Category
  api/Infrastructure/Mappings/DocumentCategoryMapping.cs
  web/src/components/case-details/civil/CivilDocumentsView.vue
  web/src/components/case-details/civil/appearances/ScheduledDocuments.vue
  web/src/components/case-details/civil/documents/AllDocuments.vue
  web/src/components/case-details/civil/documents/JudicialBinder.vue
  web/tests/components/case-details/civil/CivilDocumentsView.test.ts
Labels: bug, enhancement, javascript, .NET

#483 JASPER 577: Nutrient updates
  web/src/components/case-details/civil/CivilDocumentsView.vue
  web/src/components/case-details/criminal/CriminalDocumentsView.vue
  web/src/components/courtlist/CourtList.vue
  web/src/components/documents/NutrientContainer.vue
  web/src/components/shared.ts
  web/src/stores/PDFViewerStore.ts
  web/src/types/shared.ts
  web/tests/components/documents/NutrientContainer.test.ts
Labels: bug, enhancement, javascript

#457 jasper-121 add access request page with basic api to allow saving new…
  api/Controllers/AuthController.cs
  api/Controllers/UsersController.cs
  api/Helpers/ClaimsTypes.cs
  api/Helpers/Extensions/ClaimsPrincipalExtensions.cs
  api/Helpers/Extensions/ExceptionExtensions.cs
  api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
  api/Infrastructure/Authorization/AuthorizationRedirectMiddlewareResultHandler.cs
  api/Infrastructure/Authorization/AuthorizationServiceCollectionExtension.cs
  api/Infrastructure/Authorization/PermissionHandler.cs
  api/Infrastructure/Authorization/ProviderAuthorizationHandler.cs
  api/Models/AccessControlManagement/UserDto.cs
  api/Services/UserService.cs
  api/Startup.cs
  api/Validators/UserDtoValidator.cs
  db/Models/User.cs
  db/Seeders/UserSeeder.cs
  tests/api/Controllers/UsersControllerTests.cs
  tests/api/Infrastructure/Authorization/PermissionHandlerTests.cs
  tests/api/Services/UserServiceTests.cs
  web/package-lock.json
  web/package.json
  web/src/components/dashboard/RequestAccess.vue
  web/src/router/index.ts
  web/src/services/HttpService.ts
  web/src/services/UserService.ts
  web/src/stores/CommonStore.ts
  web/src/types/ApiResponse.ts
  web/src/types/common/index.ts
  web/src/utils/utils.ts
  web/tests/components/dashboard/RequestAccess.test.ts
  web/tests/components/dashboard/__snapshots__/RequestAccess.test.ts.snap
  web/tests/utils/utils.test.ts
  web/vitest.config.js
  web/vitest.setup.ts
Labels: enhancement

#493 JASPER 585: View court-list appearance details documents
  web/index.html
  web/src/components/case-details/civil/appearances/ScheduledDocuments.vue
  web/src/components/civil/CivilAppearanceDetails.vue
  web/src/components/courtlist/CourtListCriminalDetails.vue
  web/src/components/courtlist/CourtListTable.vue
  web/tests/components/case-details/civil/appearances/ScheduledDocuments.test.ts
  web/tests/components/civil/CivilAppearanceDetails.test.ts
  web/tests/components/courtList/CourtListCriminalDetails.test.ts
Labels: bug, enhancement, javascript

#511 Fix directory where dotnet test command executes
  .github/workflows/actions/build-api/action.yml
  .github/workflows/build-and-test-api.yml
Labels: github_actions

#530 JASPER 614: Show 'View Key-documents' for all criminal appearances
  web/src/components/courtlist/CourtListTableActionBarGroup.vue
  web/src/utils/utils.ts
  web/tests/utils/utils.test.ts
Labels: bug, javascript

#532 JASPER 588: Fix key-documents perfected bail data not showing
  web/src/components/case-details/criminal/CriminalDocumentsView.vue
  web/src/components/courtlist/CourtListCriminalDetails.vue
  web/tests/components/case-details/criminal/CriminalDocumentsView.test.ts
  web/tests/components/courtList/CourtListCriminalDetails.test.ts
Labels: bug, javascript

#533 JASPER 541/542: Court-list sorting, ordering and counting
  web/src/components/courtlist/CourtList.vue
  web/src/components/courtlist/CourtListTable.vue
Labels: bug, enhancement, javascript
