Repository bcgov/jasper, pull requests merged in 2025-05, with the labels that each got.

#311 JASPER-297: Case details: Criminal - Sentence/order details
  web/src/components/case-details/common/CaseHeader.vue
  web/src/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsDialog.vue
  web/src/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsTable.vue
  web/src/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsView.vue
  web/tests/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsDialog.test.ts
  web/tests/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsTable.test.ts
  web/tests/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsView.test.ts
Labels: enhancement, javascript

#312 JASPER 365: Civil appearance details
  api/Infrastructure/ServiceCollectionExtensions.cs
  pcss-client/Clients/FileDetailServicesClient.cs
  web/src/assets/colors.css
  web/src/components/case-details/civil/appearances/AppearanceMethods.vue
  web/src/components/case-details/civil/appearances/CivilAppearanceDetails.vue
  web/src/components/case-details/civil/appearances/ScheduledDocuments.vue
  web/src/components/case-details/civil/appearances/ScheduledParties.vue
  web/src/components/case-details/common/AppearancesView.vue
  web/src/components/case-details/common/CaseHeader.vue
  web/src/components/civil/CivilCaseDetails.vue
  web/src/plugins/vuetify.ts
  web/src/services/FilesService.ts
  web/src/types/civil/jsonTypes/index.ts
  web/tests/components/case-details/civil/appearances/AppearanceMethods.test.ts
  web/tests/components/case-details/civil/appearances/CivilAppearanceDetails.test.ts
  web/tests/components/case-details/common/AppearancesView.test.ts
Labels: javascript, .NET

#313 JASPER-380: Case Details: Criminal - File Markers to be moved to accused and updated
  web/src/components/case-details/common/accused/Accused.vue
  web/src/components/case-details/criminal/CriminalSummary.vue
  web/src/components/courtlist/CourtListTable.vue
  web/src/components/shared/FileMarkers.vue
  web/src/types/common/index.ts
  web/tests/components/case-details/common/accused/Accused.test.ts
  web/tests/components/case-details/criminal/CriminalSummary.test.ts
  web/tests/components/shared/FileMarkers.test.ts
Labels: enhancement, javascript

#320 JASPER-385: Case Details: Criminal - Traffic Participants Header/Panel
  web/src/components/case-details/common/accused/AccusedPanel.vue
  web/src/components/case-details/criminal/CriminalSidePanel.vue
  web/src/utils/utils.ts
  web/tests/components/case-details/common/accused/AccusedPanel.test.ts
Labels: bug

#321 Fix file marker description for DO and W
  web/src/components/shared/FileMarkers.vue
  web/tests/components/shared/FileMarkers.test.ts
Labels: bug

#324 JASPER 346: Criminal appearance details
  web/src/components/case-details/common/AppearancesView.vue
  web/src/components/case-details/criminal/appearances/AppearanceCharges.vue
  web/src/components/case-details/criminal/appearances/AppearanceCounsel.vue
  web/src/components/case-details/criminal/appearances/AppearanceMethods.vue
  web/src/components/case-details/criminal/appearances/CriminalAppearanceDetails.vue
  web/src/components/criminal/CriminalCaseDetails.vue
  web/src/services/FilesService.ts
  web/src/types/criminal/jsonTypes/index.ts
  web/tests/components/case-details/common/AppearancesView.test.ts
  web/tests/components/case-details/criminal/appearances/AppearanceMethods.test.ts
  web/tests/components/case-details/criminal/appearances/CriminalAppearanceDetails.test.ts
Labels: javascript

#330 JASPER-349: Case Details: Family - Birth Date and Age of Child
  api/Models/Civil/Detail/CivilParty.cs
  api/Services/Files/CivilFilesService.cs
  web/src/components/case-details/civil/children/Child.vue
  web/src/types/civil/jsonTypes/index.ts
  web/tests/components/case-details/civil/children/Child.test.ts
Labels: enhancement, javascript, .NET

#332 JASPER 409: Scrollable case-details side-panel
  web/public/styles/common.css
  web/src/components/case-details/civil/CivilSidePanel.vue
  web/src/components/case-details/criminal/CriminalSidePanel.vue
  web/src/components/civil/CivilCaseDetails.vue
  web/src/components/criminal/CriminalCaseDetails.vue
Labels: javascript

#331 JASPER-382: Court List - Update File Markers
  web/src/components/courtlist/CourtListTable.vue
  web/src/components/shared/FileMarkers.vue
  web/src/types/common/index.ts
  web/src/types/courtlist/index.ts
  web/tests/components/shared/FileMarkers.test.ts
Labels: enhancement, javascript

#334 JASPER-377: Case details: Civil - Summary: CPA/FLA Marker
  api/Models/Civil/Detail/RedactedCivilFileDetailResponse.cs
  web/src/components/case-details/civil/CivilSummary.vue
  web/src/types/civil/jsonTypes/index.ts
  web/tests/components/case-details/civil/CivilSummary.test.ts
Labels: enhancement, javascript, .NET

#337 JASPER 408: Reduce whitespace in Case-Details side-panel
  web/src/components/case-details/civil/parties/Party.vue
  web/src/components/case-details/common/accused/Accused.vue
  web/src/components/case-details/criminal/CriminalSummary.vue
Labels: javascript
