Repository bcgov/jasper, pull requests merged in 2025-10, with the labels that each got.

#541 JASPER-511: Outlook integration for JASPER account
  api/Controllers/ReservedJudgementsController.cs
  api/Helpers/Extensions/StringExtensions.cs
  api/Helpers/RecurringJobHelper.cs
  api/Infrastructure/ServiceCollectionExtensions.cs
  api/Jobs/RecurringJobBase.cs
  api/Jobs/SyncDocumentCategoriesJob.cs
  api/Jobs/SyncReservedJudgementsJob.cs
  api/Models/ReservedJudgementDto.cs
  api/Services/CourtListService.cs
  api/Services/DashboardService.cs
  api/Services/EmailService.cs
  api/Services/Files/CivilFilesService.cs
  api/Services/Files/CriminalFilesService.cs
  api/Services/Files/FilesService.cs
  api/Services/LocationService.cs
  api/Startup.cs
  api/api.csproj
  db/Models/ReservedJudgement.cs
  docker/docker-compose.yaml
  docker/openshift/sync-secrets.sh
  infrastructure/cloud/modules/SecretsManager/main.tf
  infrastructure/cloud/modules/SecretsManager/output.tf
  tests/api/Documents/Strategies/CourtSummaryReportStrategyTest.cs
  tests/api/Documents/Strategies/FileStrategyTest.cs
  tests/api/Documents/Strategies/ROPStrategyTest.cs
  tests/api/Helpers/Extensions/StringExtensionsTests.cs
  tests/api/Jobs/SyncDocumentCategoriesJobTests.cs
  tests/api/Jobs/SyncReservedJudgementsTests.cs
  tests/api/Services/CourtListServiceTests.cs
Labels: enhancement, .NET, infrastructure

#542 JASPER 88: Show full ReservedJudgement table data
  web/src/components/courtlist/CourtList.vue
  web/src/components/dashboard/panels/DashboardPanels.vue
  web/src/components/dashboard/panels/reserved-judgements/ReservedJudgementTable.vue
  web/src/types/ReservedJudgement.ts
  web/tests/components/dashboard/panels/DashboardPanels.test.ts
Labels: bug, enhancement, javascript

#544 Reload Reserved Judgments when User Selects Different Judge
  web/src/components/dashboard/Dashboard.vue
  web/src/components/dashboard/panels/DashboardPanels.vue
  web/src/components/dashboard/panels/reserved-judgements/ReservedJudgementTable.vue
Labels: javascript

#545 Upgrade BE packages
  api/api.csproj
  db/db.csproj
  jc-interface-client/jc-interface-client.csproj
  pcss-client/pcss-client.csproj
  tests/tests.csproj
Labels: dependencies, .NET

#555 JASPER-556: Dashboard: Addition of date navigation chevrons to move forward or backward
  web/src/components/dashboard/CalendarToolbar.vue
  web/src/components/dashboard/CourtToday.vue
  web/src/components/dashboard/Dashboard.vue
  web/src/components/dashboard/court-calendar/CourtCalendar.vue
  web/src/components/dashboard/my-calendar/MyCalendar.vue
  web/tests/components/dashboard/CalendarToolbar.test.ts
  web/tests/components/dashboard/court-calendar/CourtCalendar.test.ts
  web/tests/components/dashboard/my-calendar/MyCalendar.test.ts
Labels: enhancement, javascript

#557 JASPER 546: Show court-list schedule notes
  web/src/components/courtlist/CourtListTable.vue
  web/src/components/shared/TooltipIcon.vue
Labels: enhancement, javascript
