Repository bcgov/jasper, pull requests merged in 2025-04, with the labels that each got.

#255 Fix authentication failure when logging in to JASPER
  api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
  api/Infrastructure/ServiceCollectionExtensions.cs
Labels: bug

#254 JASPER-344: Court list - Print
  api/Controllers/CourtListController.cs
  api/Services/CourtListService.cs
  pcss-client/Clients/ReportServicesClient.cs
  tests/api/Controllers/CourtListControllerTests.cs
  tests/api/Services/CourtListServiceTests.cs
  web/src/components/courtlist/CourtList.vue
  web/src/components/courtlist/CourtListSearch.vue
  web/src/components/courtlist/CourtListTableSearch.vue
  web/src/components/courtlist/CourtListTableSearchDialog.vue
  web/src/services/CourtListService.ts
  web/src/services/LookupService.ts
  web/src/services/index.ts
  web/src/types/common/index.ts
  web/tests/components/courtList/CourtListTableSearchDialog.test.ts
Labels: enhancement, javascript, .NET

#257 JASPER-239: Court List - Print v2
  aws/services/apiService.ts
  aws/services/httpService.ts
  aws/tests/services/apiService.test.ts
  openshift/sync-secrets.dc.yaml
  pcss-client/Clients/ReportServicesClient.cs
  web/src/components/courtlist/CourtList.vue
  web/src/components/courtlist/CourtListSearch.vue
  web/src/components/courtlist/CourtListTableSearchDialog.vue
  web/tests/components/courtList/CourtListTableSearchDialog.test.ts
Labels: enhancement, javascript

#256 JASPER: 241 - Court list table
  web/public/styles/common.css
  web/src/components/courtlist/CourtList.vue
  web/src/components/courtlist/CourtListTable.vue
  web/src/components/shared/FileMarkers.vue
  web/src/types/courtlist/index.ts
  web/src/types/criminal/jsonTypes/index.ts
  web/tests/components/shared/FileMarkers.test.ts
Labels: bug, enhancement, javascript

#261 JASPER-239: Print Court List - Print
  web/src/components/courtlist/CourtList.vue
Labels: bug, javascript

#265 JASPER 296: Case details appearances view core functionality
  web/src/components/case-details/Accused/Accused.vue
  web/src/components/case-details/Accused/Bans.vue
  web/src/components/case-details/AppearancesView.vue
  web/src/components/case-details/CaseHeader.vue
  web/src/components/courtlist/CourtListTable.vue
  web/src/components/criminal/CriminalCaseDetails.vue
  web/src/components/shared/AppearanceStatusChip.vue
  web/src/utils/dateUtils.ts
  web/src/utils/utils.ts
  web/tests/components/case-details/AppearancesView.test.ts
  web/tests/components/case-details/CaseHeader.test.ts
  web/tests/components/shared/AppearanceStatusChip.test.ts
  web/tests/utils/dateUtils.test.ts
Labels: enhancement, javascript

#266 JASPER-282: Case details: Criminal - Adjudicator Restrictions
  api/Controllers/AuthController.cs
  api/Helpers/ClaimsTypes.cs
  api/Helpers/Extensions/ClaimsPrincipalExtensions.cs
  api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
  api/Models/AccessControlManagement/UserDto.cs
  api/Services/Files/CriminalFilesService.cs
  api/Services/UserService.cs
  db/Models/Role.cs
  db/Seeders/GroupSeeder.cs
  db/Seeders/RoleSeeder.cs
  tests/api/Helpers/Extensions/ClaimsPrincipalExtensionsTests.cs
  tests/api/Infrastructure/Authorization/PermissionHandlerTests.cs
  tests/api/Services/UserServiceTests.cs
  web/src/assets/colors.css
  web/src/components/case-details/Accused/AccusedPanel.vue
  web/src/components/case-details/AdjudicatorRestrictions/AdjudicatorRestriction.vue
  web/src/components/case-details/AdjudicatorRestrictions/AdjudicatorRestrictionsPanel.vue
  web/src/components/case-details/CriminalSidePanel.vue
  web/src/components/criminal/CriminalCaseDetails.vue
  web/src/main.ts
  web/tests/components/case-details/AdjudicatorRestrictions/AdjudicatorRestriction.test.ts
  web/tests/components/case-details/AdjudicatorRestrictions/AdjudicatorRestrictionsPanel.test.ts
  web/tests/components/case-details/CriminalSidePanel.test.ts
Labels: enhancement, javascript, .NET

#267 JASPER 296 - Case-details accused filter
  web/src/components/case-details/AppearancesView.vue
  web/tests/components/case-details/AppearancesView.test.ts
Labels: enhancement, javascript

#269 JASPER 280: Criminal case-details Documents view core functionality
  web/public/styles/common.css
  web/src/assets/colors.css
  web/src/components/case-details/CaseHeader.vue
  web/src/components/case-details/DocumentsView.vue
  web/src/components/courtfilesearch/CourtFileSearchResult.vue
  web/tests/components/case-details/CaseHeader.test.ts
  web/tests/components/case-details/DocumentsView.test.ts
Labels: enhancement, javascript

#283 Reorganized case-details folder structure and naming convention
  web/src/components/case-details/civil/CivilSidePanel.vue
  web/src/components/case-details/common/AppearancesView.vue
  web/src/components/case-details/common/CaseHeader.vue
  web/src/components/case-details/common/CourtFilesSelector.vue
  web/src/components/case-details/common/DivisionBadge.vue
  web/src/components/case-details/common/DocumentsView.vue
  web/src/components/case-details/common/Summary.vue
  web/src/components/case-details/common/accused/Accused.vue
  web/src/components/case-details/common/accused/AccusedPanel.vue
  web/src/components/case-details/common/accused/Bans.vue
  web/src/components/case-details/common/adjudicator-restrictions/AdjudicatorRestriction.vue
  web/src/components/case-details/common/adjudicator-restrictions/AdjudicatorRestrictionsPanel.vue
  web/src/components/case-details/criminal/CriminalSidePanel.vue
  web/src/components/civil/CivilCaseDetails.vue
  web/src/components/criminal/CriminalCaseDetails.vue
  web/tests/components/case-details/DivisionBadge.test.ts
  web/tests/components/case-details/Summary.test.ts
  web/tests/components/case-details/civil/CivilSidePanel.test.ts
  web/tests/components/case-details/common/AppearancesView.test.ts
  web/tests/components/case-details/common/CaseHeader.test.ts
  web/tests/components/case-details/common/CourtFilesSelector.test.ts
  web/tests/components/case-details/common/DivisionBadge.test.ts
  web/tests/components/case-details/common/DocumentsView.test.ts
  web/tests/components/case-details/common/Summary.test.ts
  web/tests/components/case-details/common/accused/Accused.test.ts
  web/tests/components/case-details/common/accused/AccusedPanel.test.ts
  web/tests/components/case-details/common/accused/Bans.test.ts
  web/tests/components/case-details/common/adjudicator-restrictions/AdjudicatorRestriction.test.ts
  web/tests/components/case-details/common/adjudicator-restrictions/AdjudicatorRestrictionsPanel.test.ts
  web/tests/components/case-details/criminal/CriminalSidePanel.test.ts
Labels: javascript

#292 JASPER-327: Case details: Civil - Summary: Family and Small Claims
  api/Models/Civil/Detail/RedactedCivilFileDetailResponse.cs
  web/src/assets/colors.css
  web/src/components/case-details/civil/CivilSidePanel.vue
  web/src/components/case-details/civil/CivilSummary.vue
  web/src/components/case-details/civil/SheriffCommentsDialog.vue
  web/src/components/case-details/common/CourtFilesSelector.vue
  web/src/components/case-details/common/DivisionBadge.vue
  web/src/components/case-details/criminal/CriminalSidePanel.vue
  web/src/components/case-details/criminal/CriminalSummary.vue
  web/src/components/civil/CivilCaseDetails.vue
  web/tests/components/case-details/civil/CivilSidePanel.test.ts
  web/tests/components/case-details/civil/CivilSummary.test.ts
  web/tests/components/case-details/civil/SheriffComments.test.ts
  web/tests/components/case-details/common/DivisionBadge.test.ts
  web/tests/components/case-details/criminal/CriminalSidePanel.test.ts
  web/tests/components/case-details/criminal/CriminalSummary.test.ts
Labels: enhancement, javascript

#293 JASPER 328 - Civil Documents view
  web/src/components/case-details/civil/CivilDocumentsView.vue
  web/src/components/case-details/common/CaseHeader.vue
  web/src/components/case-details/criminal/CriminalDocumentsView.vue
  web/src/components/shared/EllipsesMenu.vue
  web/tests/components/case-details/civil/CivilDocumentsView.test.ts
  web/tests/components/case-details/criminal/CriminalDocumentsView.test.ts
  web/tests/components/shared/EllipsesMenu.test.ts
Labels: enhancement, javascript

#295 JASPER-324: Case details: Civil - Small Claims - Parties Information
  api/Models/Civil/Detail/CivilParty.cs
  api/Models/Location/Location.cs
  api/Services/Files/CivilFilesService.cs
  api/Services/LocationService.cs
  tests/api/Models/Location/LocationTests.cs
  web/src/assets/colors.css
  web/src/components/case-details/civil/CivilSidePanel.vue
  web/src/components/case-details/civil/parties/PartiesPanel.vue
  web/src/components/case-details/civil/parties/Party.vue
  web/src/components/shared/LabelWithTooltip.vue
  web/src/types/civil/jsonTypes/index.ts
  web/tests/components/case-details/civil/CivilSidePanel.test.ts
  web/tests/components/case-details/civil/parties/PartiesPanel.test.ts
  web/tests/components/case-details/civil/parties/Party.test.ts
  web/tests/components/shared/LabelWithTooltip.test.ts
Labels: enhancement, javascript, .NET

#294 JASPER 328: Civil case-details FiledBy
  api/Controllers/CodesController.cs
  api/Services/LookupService.cs
  web/src/components/case-details/civil/CivilDocumentsView.vue
  web/src/components/shared/EllipsesMenu.vue
  web/src/components/shared/LabelWithTooltip.vue
  web/src/services/LookupService.ts
  web/src/stores/CommonStore.ts
  web/src/types/common/index.ts
  web/src/types/shared.ts
  web/src/utils/utils.ts
  web/tests/components/case-details/civil/CivilDocumentsView.test.ts
Labels: enhancement, javascript, .NET

#301 JASPER-325: Case details: Civil - Family - Parties and Children Information
  api/Services/Files/CivilFilesService.cs
  web/src/components/case-details/civil/CivilSidePanel.vue
  web/src/components/case-details/civil/children/Child.vue
  web/src/components/case-details/civil/children/ChildrenPanel.vue
  web/src/components/case-details/civil/parties/PartiesPanel.vue
  web/src/components/case-details/civil/parties/Party.vue
  web/src/components/case-details/common/CourtFilesSelector.vue
  web/src/components/courtfilesearch/CourtFileSearchView.vue
  web/src/types/common/index.ts
  web/src/types/courtFileSearch/index.ts
  web/tests/components/case-details/civil/CivilSidePanel.test.ts
  web/tests/components/case-details/civil/children/Child.test.ts
  web/tests/components/case-details/civil/children/ChildrenPanel.test.ts
  web/tests/components/case-details/civil/parties/PartiesPanel.test.ts
  web/tests/components/case-details/civil/parties/Party.test.ts
  web/tests/components/case-details/common/CourtFilesSelector.test.ts
Labels: enhancement, javascript, .NET

#303 Upgrade backend packages to latest including MongoDb.EFCore to v9.0
  api/api.csproj
  db/db.csproj
  jc-interface-client/jc-interface-client.csproj
  pcss-client/pcss-client.csproj
  tests/tests.csproj
Labels: dependencies, .NET
