Repository bcgov/jasper, pull requests merged in 2025-08, with the labels that each got.

#424 JASPER 454 - Remove selected binder docs
  web/src/components/case-details/civil/CivilDocumentsView.vue
  web/src/components/case-details/civil/documents/JudicialBinder.vue
  web/src/components/case-details/criminal/CriminalDocumentsView.vue
  web/src/plugins/vuetify.ts
  web/tests/components/case-details/civil/CivilDocumentsView.test.ts
  web/tests/components/case-details/civil/documents/JudicialBinder.test.ts
Labels: enhancement, javascript

#430 JASPER-363: Dashboard - Court Calendar - Date selections
  api/Controllers/DashboardController.cs
  api/Helpers/ClaimsTypes.cs
  api/Helpers/Extensions/ClaimsPrincipalExtensions.cs
  api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
  api/Models/Calendar/Activity.cs
  api/Models/Calendar/CalendarDayActivity.cs
  api/Models/Calendar/CalendarSchedule.cs
  api/Models/Calendar/CourtCalendarSchedule.cs
  api/Models/Calendar/Presider.cs
  api/Services/DashboardService.cs
  docker/docker-compose.yaml
  infrastructure/cloud/modules/SecretsManager/main.tf
  infrastructure/cloud/modules/SecretsManager/output.tf
  tests/api/Controllers/DashboardControllerTests.cs
  tests/api/Services/DashboardServiceTests.cs
  web/package-lock.json
  web/package.json
  web/src/assets/month.svg
  web/src/assets/one-week.svg
  web/src/assets/two-week.svg
  web/src/components/dashboard/CalendarToolbar.vue
  web/src/components/dashboard/CourtToday.vue
  web/src/components/dashboard/Dashboard.vue
  web/src/components/dashboard/MonthPicker.vue
  web/src/components/dashboard/court-calendar/CourtCalendar.vue
  web/src/components/dashboard/court-calendar/CourtCalendarToolbar.vue
  web/src/components/dashboard/my-calendar/MyCalendar.vue
  web/src/components/dashboard/my-calendar/MyCalendarDay.vue
  web/src/components/dashboard/my-calendar/MyCalendarDayExpanded.vue
  web/src/services/DashboardService.ts
  web/src/types/CourtCalendarSchedule.ts
  web/src/types/common/index.ts
  web/src/types/index.ts
  web/tests/components/dashboard/CalendarToolbar.test.ts
  web/tests/components/dashboard/CourtToday.test.ts
  web/tests/components/dashboard/Dashboard.test.ts
  web/tests/components/dashboard/MonthPicker.test.ts
  web/tests/components/dashboard/MyCalendar.test.ts
  web/tests/components/dashboard/court-calendar/CourtCalendar.test.ts
  web/tests/components/dashboard/my-calendar/MyCalendar.test.ts
  web/tests/components/dashboard/my-calendar/MyCalendarDay.test.ts
  web/tests/components/dashboard/my-calendar/MyCalendarDayExpanded.test.ts
  web/vite.config.js
Labels: javascript, .NET, infrastructure

#433 Fix Court-list appearance details not showing all key-documents
  api/Models/Criminal/AppearanceDetail/CriminalAppearanceDetail.cs
  api/Services/Files/CriminalFilesService.cs
  web/src/components/courtlist/CourtList.vue
  web/src/components/courtlist/CourtListCriminalDetails.vue
  web/src/types/criminal/jsonTypes/index.ts
  web/tests/components/courtList/CourtListCriminalDetails.test.ts
Labels: bug, javascript, .NET

#434 JASPER 527: Retrieve document info strategies
  api/Documents/DocumentMerger.cs
  api/Documents/DocumentRetriever.cs
  api/Documents/DocumentType.cs
  api/Documents/IDocumentRetriever.cs
  api/Documents/Strategies/CourtSummaryReportStrategy.cs
  api/Documents/Strategies/FileStrategy.cs
  api/Documents/Strategies/IDocumentStrategy.cs
  api/Documents/Strategies/ROPStrategy.cs
  api/Documents/Strategies/ReportStrategy.cs
  api/Infrastructure/ServiceCollectionExtensions.cs
  api/Models/Document/PdfDocumentDetailsRequest.cs
  api/Models/Document/PdfDocumentRequest.cs
  tests/api/Documents/DocumentMergerTests.cs
  tests/api/Documents/DocumentRetrieverTests.cs
  tests/api/Documents/Strategies/CourtSummaryReportStrategyTest.cs
  tests/api/Documents/Strategies/FileStrategyTest.cs
  tests/api/Documents/Strategies/ROPStrategyTest.cs
Labels: enhancement, .NET

#436 JASPER 526: Expose new document generation endpoint
  api/Controllers/FilesController.cs
  api/Documents/Strategies/FileStrategy.cs
  api/Models/Document/PdfDocumentDetailsRequest.cs
  web/src/components/case-details/civil/CivilDocumentsView.vue
  web/src/components/case-details/criminal/CriminalDocumentsView.vue
  web/src/components/courtlist/CourtList.vue
  web/src/components/documents/DocumentUtils.ts
  web/src/components/documents/NutrientContainer.vue
  web/src/components/documents/models/GeneratePdf.ts
  web/src/components/shared.ts
  web/src/services/FilesService.ts
  web/src/stores/PDFViewerStore.ts
  web/src/types/shared.ts
  web/tests/components/documents/DocumentUtils.test.ts
  web/tests/components/documents/NutrientContainer.test.ts
Labels: enhancement, javascript, .NET

#440 JASPER-402: Dashboard - Court Calendar - Date Box
  api/Models/Calendar/CalendarDayActivity.cs
  api/Services/DashboardService.cs
  tests/api/Services/DashboardServiceTests.cs
Labels: enhancement, .NET

#450 JASPER 465: Open Judicial-Binder in Nutrient
  web/src/components/case-details/civil/CivilDocumentsView.vue
  web/src/components/case-details/civil/documents/JudicialBinder.vue
  web/src/components/civil/CivilCaseDetails.vue
  web/src/components/criminal/CriminalCaseDetails.vue
Labels: bug, enhancement, javascript

#452 Fix missing env variable when syncing updating AWS credentials
  docker/openshift/update-aws-creds.sh
  openshift/update-aws-creds.dc.yaml
Labels: bug

#461 JASPER-557: Performance Tuning: Case Details Load (Timeout Removal)
  web/src/services/HttpService.ts
Labels: javascript

#463 JASPER-569: Court List: Temporary updates to elements on page
  web/src/components/courtlist/CourtListCard.vue
  web/src/components/courtlist/CourtListTable.vue
  web/src/components/courtlist/CourtListTableActionBarGroup.vue
  web/tests/components/courtList/CourtListTableActionBarGroup.test.ts
Labels: enhancement, javascript

#462 JASPER 470 - Nutrient Viewer Document Outline
  web/src/components/case-details/civil/CivilDocumentsView.vue
  web/src/components/case-details/criminal/CriminalDocumentsView.vue
  web/src/components/courtlist/CourtList.vue
  web/src/components/documents/DocumentUtils.ts
  web/src/components/documents/NutrientContainer.vue
  web/src/components/documents/models/GeneratePdf.ts
  web/src/components/shared.ts
  web/src/stores/PDFViewerStore.ts
  web/tests/components/documents/DocumentUtils.test.ts
  web/tests/components/documents/NutrientContainer.test.ts
Labels: enhancement, javascript
