Repository bcgov/jasper, pull requests merged in 2025-07, with the labels that each got.

#384 JASPER 360: Court-list civil appearance details
  web/src/components/case-details/civil/appearances/CivilAppearanceDetails.vue
  web/src/components/case-details/common/AppearancesView.vue
  web/src/components/civil/CivilAppearanceDetails.vue
  web/src/components/courtlist/CourtListCriminalDetails.vue
  web/src/components/courtlist/CourtListTable.vue
  web/tests/components/civil/CivilAppearanceDetails.test.ts
  web/web.njsproj
Labels: javascript

#386 JASPER 474: Copyable file-number and center tabs
  web/public/styles/common.css
  web/src/components/case-details/civil/CivilSummary.vue
  web/src/components/case-details/common/CourtFilesSelector.vue
  web/src/components/case-details/criminal/CriminalSummary.vue
  web/src/components/civil/CivilCaseDetails.vue
  web/src/components/courtfilesearch/CourtFileSearchResult.vue
  web/src/components/courtfilesearch/CourtFileSearchView.vue
  web/src/components/criminal/CriminalCaseDetails.vue
  web/src/components/shared/CopyToClipboard.vue
  web/src/constants/labelClasses.ts
  web/tests/components/case-details/criminal/CriminalSummary.test.ts
  web/tests/components/shared/CopyToClipboard.test.ts
Labels: javascript

#394 JASPER-467: Case Details: Civil - Appearance of Aliases
  api/Services/Files/CivilFilesService.cs
  web/src/components/case-details/civil/parties/Party.vue
  web/tests/components/case-details/civil/parties/Party.test.ts
Labels: bug, javascript

#400 JASPER 310: My court-list
  api/Controllers/CourtListController.cs
  api/Services/CourtListService.cs
  pcss-client/Clients/SearchDateServicesClient.cs
  web/src/components/courtlist/CourtList.vue
  web/src/components/courtlist/CourtListSearch.vue
  web/src/services/CourtListService.ts
  web/tests/components/courtList/CourtListSearch.test.ts
Labels: enhancement, javascript, .NET

#401 JASPER 279 - Criminal Key Documents
  api/Models/Criminal/Detail/CriminalParticipant.cs
  web/src/components/case-details/criminal/CriminalDocumentsView.vue
  web/src/types/criminal/jsonTypes/index.ts
  web/tests/components/case-details/criminal/CriminalDocumentsView.test.ts
Labels: enhancement, javascript, .NET

#403 JASPER-86 and 478: Dashboard - My Schedule - Click to Expand a Date & Adjudicator Restrictions
  api/Models/Calendar/CalendarDay.cs
  api/Models/Calendar/CalendarDayActivity.cs
  api/Services/DashboardService.cs
  tests/api/Services/DashboardServiceTests.cs
  web/src/components/dashboard/MyCalendar.vue
  web/src/components/dashboard/MyCalendarDay.vue
  web/src/components/dashboard/MyCalendarDayExpanded.vue
  web/src/types/CalendarDayActivity.ts
  web/tests/components/dashboard/MyCalendarDayExpanded.test.ts
Labels: javascript, .NET

#415 JASPER 454 - Delete Judicial Binder/Remove Associated Documents
  web/src/components/case-details/civil/CivilDocumentsView.vue
  web/src/components/case-details/civil/documents/AllDocuments.vue
  web/src/components/case-details/civil/documents/JudicialBinder.vue
  web/src/components/shared/ConfirmButton.vue
  web/tests/components/case-details/civil/documents/JudicialBinder.test.ts
  web/tests/components/shared/ConfirmButton.test.ts
Labels: enhancement, javascript

#414 JASPER-384: Design Document Category Access from PCSS
  api/Helpers/RecurringJobHelper.cs
  api/Infrastructure/Authorization/HangFireDashboardAuthorizationFilter.cs
  api/Infrastructure/Mappings/DocumentCategoryMapping.cs
  api/Infrastructure/ServiceCollectionExtensions.cs
  api/Jobs/IRecurringJob.cs
  api/Jobs/SyncDocumentCategoriesJob.cs
  api/Models/DocumentCategoryDto.cs
  api/Services/CourtListService.cs
  api/Services/DocumentCategoryService.cs
  api/Services/Files/CivilFilesService.cs
  api/Services/Files/CriminalFilesService.cs
  api/Services/LookupService.cs
  api/Startup.cs
  api/api.csproj
  api/appsettings.json
  db/Contants/CollectionNameConstants.cs
  db/Contexts/JasperDbContext.cs
  db/Models/DocumentCategory.cs
  pcss-client/Clients/ApiException.cs
  pcss-client/Clients/ConfigurationServicesClient.cs
  pcss-client/Models/Models.cs
  tests/api/Controllers/CourtListControllerTests.cs
  tests/api/Controllers/FilesControllerTests.cs
  tests/api/Jobs/SyncDocumentCategoriesJobTests.cs
  tests/api/Services/DocumentCategoryServiceTests.cs
  tests/api/Services/LookupServiceTests.cs
Labels: enhancement, .NET

#421 JASPER 455: Judicial binder reordering
  web/package-lock.json
  web/package.json
  web/src/components/case-details/civil/CivilDocumentsView.vue
  web/src/components/case-details/civil/documents/JudicialBinder.vue
  web/src/components/courtlist/CourtListTable.vue
  web/tests/components/case-details/civil/children/Child.test.ts
  web/tests/components/case-details/civil/documents/JudicialBinder.test.ts
Labels: enhancement, javascript

#423 JASPER 499/471 - Court-list key documents
  api/Helpers/Documents/KeyDocumentResolver.cs
  api/Models/Criminal/AppearanceDetail/CriminalAppearanceDetail.cs
  api/Models/Criminal/Detail/CriminalParticipant.cs
  db/Models/DocumentCategory.cs
  tests/api/Helpers/Documents/KeyDocumentResolverTests.cs
  web/src/components/case-details/criminal/CriminalDocumentsView.vue
  web/src/components/courtlist/CourtListCriminalDetails.vue
  web/tests/components/courtList/CourtListCriminalDetails.test.ts
Labels: bug, enhancement, javascript, .NET
